version = 1

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  environment = ["wordpress"]
  # You can keep complexity or style ignores here if you still want them off:
  ignore_rules = ["PHP-R1006", "PHP-T1002"]

[[analyzers]]
name = "javascript"
enabled = true